// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Configuration;

namespace ToDoList.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191007002708_Migration-01")]
    partial class Migration01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ToDoList.Models.Task", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("deadline");

                    b.Property<string>("name");

                    b.Property<int>("percentageCompleted");

                    b.Property<double>("priority");

                    b.HasKey("id");

                    b.ToTable("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
